import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/NavBar";
import Footer from "@/components/layout/Footer";

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"]
})

// export const metadata = {
//   title: {
//     default: "Hero Kidz",
//     template: "%s | Hero Kidz"
//   },
//   description: "Generated by create next app",
// };

export const metadata = {
  title: {
    default: "Hero Kidz | Build a Bright Future for Your Child",
    template: "%s | Hero Kidz",
  },
  description:
    "Hero Kidz helps children grow with quality education, creativity, and care. Give your child a brighter future today.",

  keywords: [
    "Hero Kidz",
    "Kids education",
    "Child development",
    "Kids learning platform",
    "Future for children",
    "Education for kids Bangladesh",
  ],

  authors: [{ name: "Hero Kidz Team" }],
  creator: "Hero Kidz",

  icons: {
    icon: "https://i.ibb.co/Txqm7j30/logo.png",
  },

  openGraph: {
    title: "Hero Kidz | Build a Bright Future for Your Child",
    description:
      "Hero Kidz is dedicated to shaping a better future for children through learning, care, and creativity.",
    url: "https://hero-kidz-cyan.vercel.app/",
    siteName: "Hero Kidz",
    images: [
      {
        url: "https://i.ibb.co/k2M7ddS2/image.png",
        width: 1200,
        height: 630,
        alt: "Hero Kidz Home Page",
      },
    ],
    type: "website",
  },

  twitter: {
    card: "summary_large_image",
    title: "Hero Kidz | Build a Bright Future for Your Child",
    description:
      "A trusted platform focused on kids education, creativity, and growth.",
    images: ["https://i.ibb.co/k2M7ddS2/image.png"],
  },

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
    },
  },
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          <header className="py-2">
            <NavBar></NavBar>
          </header>
          <main className="py-2 mt-16 flex-1">
            {children}
          </main>
          <footer className="py-2">
            <Footer></Footer>
          </footer>
        </div>
      </body>
    </html>
  );
}
