import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/NavBar";
import Footer from "@/components/layout/Footer";

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          <header className="py-2 md:w-11/12 mx-auto">
            <NavBar></NavBar>
          </header>
          <main className="py-2 md:w-11/12 mx-auto flex-1">
            {children}
          </main>
          <footer className="py-2 md:w-11/12 mx-auto">
            <Footer></Footer>
          </footer>
        </div>
      </body>
    </html>
  );
}
