import Products from '@/components/Home/Products';
import React from 'react';

export const metadata = {
  title: "All Products",
  description: "Generated by create next app",
};

const ProductsPage = () => {
    return (
        <div>
            <Products></Products>
        </div>
    );
};

export default ProductsPage;